### ISSUE TITLE
Adding a file into the stream instead of writing to an external file

### ISSUE THREAD

**Issue by dgieselaar** [jquense/gulp-babel-helpers#2]
Hi,

thank you for your work! 

I'd like to add the file with the helpers back into the stream, instead of writing to an external file. This would make my build process much simpler, as I now have to fiddle w/ runSequence, addsrc, etc. Is this possible?

**Comment by jquense** [comment]
Hey there,

I am not sure if it is technically possible in a gulp plugin...but before that I would like to ask, why you want this behavior? It might be helpful for me to see your use case

**Comment by dgieselaar** [comment]
I'm currently transpiling every source file individually with gulp-remember & gulp-cached, and then I concat all the files (including the file with the external helpers). Here's my gulpfile (w/ the relevant parts): https://gist.github.com/plestik/39c9ad1528c82de69f73.

If `gulp-babel-helpers` would add the external helper file back into the stream instead of writing to an external file, I could drop the entire `helper` task.

**Comment by jquense** [comment]
If you are just concatenating the helpers to the top of the file, why use external helpers at all? The default behavior is to just inline the helpers at the top of each file, which seems to be what you are trying to do, which which case the normal gulp-babel will work just fine for you.

In any case, unfortunately I don't have the time or the motivation to try and figure out a change like this. This module was built to solve a very specific use case, and I am happy with it for my own use. If you want to send a PR for this, I'd be happy to accept it as long as it didn't break my original use case. Thanks again for taking the time to file this!

**Comment by dgieselaar** [comment]
@jquense because the helpers get injected into every single file individually. So after concatenating, the helpers appear multiple times in the concatenated file (the process is basically `babel > uglify > concat`). I'll give it a shot and report back here in a few days (hopefully).
